/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifms.loja.uf.view;

import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author djgiu
 */
public class UfFormulario extends javax.swing.JPanel {

    /**
     * Creates new form UfFormulario
     */
    public UfFormulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUfNome = new javax.swing.JLabel();
        labelSigla = new javax.swing.JLabel();
        campoUfNome = new javax.swing.JTextField();
        campoSigla = new javax.swing.JTextField();
        labelICMS = new javax.swing.JLabel();
        campoICMS = new javax.swing.JTextField();

        labelUfNome.setText("Nome");

        labelSigla.setText("Sigla");

        campoUfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUfNomeActionPerformed(evt);
            }
        });

        labelICMS.setText("ICMS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(labelUfNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(labelSigla)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoUfNome)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(labelICMS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoICMS, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUfNome)
                    .addComponent(campoUfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSigla)
                    .addComponent(campoSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelICMS)
                    .addComponent(campoICMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoUfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUfNomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoICMS;
    private javax.swing.JTextField campoSigla;
    private javax.swing.JTextField campoUfNome;
    private javax.swing.JLabel labelICMS;
    private javax.swing.JLabel labelSigla;
    private javax.swing.JLabel labelUfNome;
    // End of variables declaration//GEN-END:variables

    public JTextField getCampoICMS() {
        return campoICMS;
    }

    public void setCampoICMS(JTextField campoICMS) {
        this.campoICMS = campoICMS;
    }

    public JTextField getCampoSigla() {
        return campoSigla;
    }

    public void setCampoSigla(JTextField campoSigla) {
        this.campoSigla = campoSigla;
    }

    public JTextField getCampoUf() {
        return campoUfNome;
    }

    public void setCampoUf(JTextField campoUf) {
        this.campoUfNome = campoUf;
    } 

    public JLabel getLabelICMS() {
        return labelICMS;
    }

    public void setLabelICMS(JLabel labelICMS) {
        this.labelICMS = labelICMS;
    }

    public JLabel getLabelSigla() {
        return labelSigla;
    }

    public void setLabelSigla(JLabel labelSigla) {
        this.labelSigla = labelSigla;
    }

    public JLabel getLabelUf() {
        return labelUfNome;
    }

    public void setLabelUf(JLabel labelUf) {
        this.labelUfNome = labelUf;
    }
    
}



